title: 'offline.mall::lang.common.categories'
modelClass: OFFLINE\Mall\Models\Category
list: $/offline/mall/models/category/columns.yaml
recordUrl: 'offline/mall/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
showTree: 1
treeExpanded: 1
