title: 'offline.mall::lang.common.brands'
modelClass: OFFLINE\Mall\Models\Brand
list: $/offline/mall/models/brand/columns.yaml
recordUrl: 'offline/mall/brands/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
