title: 'offline.mall::lang.common.taxes'
modelClass: OFFLINE\Mall\Models\Tax
list: $/offline/mall/models/tax/columns.yaml
recordUrl: 'offline/mall/taxes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
